"""
Post-install setup: seed default Lexington machine data.
Called from hooks.py after_install.
"""
import frappe


LEXINGTON_MACHINES = [
    {
        "machine_id": "126",
        "machine_name": '100" Flexo Press',
        "department": "Print",
        "enabled": 1,
        "speed_value": 500,
        "speed_unit": "per hour",
        "tops": 1,
        "feed_position": "Top",
        "blank_min_length": 25,
        "blank_min_width": 30,
        "blank_max_length": 100,
        "blank_max_width": 199,
        "panel_min_length": 4,
        "panel_max_length": 10.375,
        "panel_min_width": 3,
        "panel_max_width": 100,
        "panel_min_depth": 3,
        "panel_max_depth": 0,
        "can_print": 1,
        "print_stations": 1,
        "max_print_length": 96,
        "max_print_width": 189,
        "can_score_slot": 0,
        "can_die_cut": 0,
        "can_glue": 0,
        "can_stitch": 0,
        "can_fold": 0,
        "skip_feed": 0,
        "hand_feed": 0,
        "feed_edge": "Slate Feed",
        "rate_msf": 55,
        "setup_time_min": 30,
        "setup_cost": 75,
        "special_notes": "Max Print 96\" x 189\". No Skip Feed. Slate Feed.",
    },
    {
        "machine_id": "146",
        "machine_name": '37" Lang FFG',
        "department": "Fold/Glue",
        "enabled": 1,
        "speed_value": 250,
        "speed_unit": "per minute",
        "tops": 2,
        "feed_position": "Top",
        "blank_min_length": 13,
        "blank_min_width": 25,
        "blank_max_length": 42,
        "blank_max_width": 92,
        "panel_min_length": 4.75,
        "panel_max_length": 34,
        "panel_min_width": 6.75,
        "panel_max_width": 33,
        "panel_min_depth": 2,
        "panel_max_depth": 0,
        "can_print": 1,
        "print_stations": 2,
        "max_print_length": 36,
        "max_print_width": 90,
        "can_score_slot": 1,
        "can_die_cut": 0,
        "can_glue": 1,
        "glue_type": "Inside/Outside",
        "glue_tab_inches": 1.75,
        "can_stitch": 0,
        "can_fold": 1,
        "skip_feed": 1,
        "hand_feed": 0,
        "feed_edge": "LE (Leading Edge)",
        "max_unfolded_width": 65,
        "fold_clearance": 7.5,
        "rate_msf": 55,
        "setup_time_min": 20,
        "setup_cost": 50,
        "special_notes": "Need 7.5\" to fold. Max Unfolded 65\". Max Print Area 36\" x 90\". LE feed.",
    },
    {
        "machine_id": "148",
        "machine_name": '47" Apstar FFG',
        "department": "Fold/Glue",
        "enabled": 1,
        "speed_value": 240,
        "speed_unit": "per minute",
        "tops": 4,
        "feed_position": "Bottom",
        "blank_min_length": 14,
        "blank_min_width": 25,
        "blank_max_length": 59,
        "blank_max_width": 110,
        "panel_min_length": 6,
        "panel_max_length": 43,
        "panel_min_width": 7,
        "panel_max_width": 43,
        "panel_min_depth": 0,
        "panel_max_depth": 0,
        "can_print": 1,
        "print_stations": 4,
        "max_print_length": 0,
        "max_print_width": 0,
        "can_score_slot": 1,
        "can_die_cut": 1,
        "die_cut_position": "Top",
        "can_glue": 1,
        "glue_type": "Inside/Outside",
        "glue_tab_inches": 1.75,
        "can_stitch": 0,
        "can_fold": 1,
        "skip_feed": 1,
        "hand_feed": 0,
        "feed_edge": "",
        "rate_msf": 55,
        "setup_time_min": 25,
        "setup_cost": 60,
        "special_notes": "4-Bottom feed. Inside/Outside glue. Die Cut Top. Skip Feed.",
    },
    {
        "machine_id": "118",
        "machine_name": "SBS Auto Box",
        "department": "Auto Box",
        "enabled": 1,
        "speed_value": 0,
        "speed_unit": "per hour",
        "tops": 1,
        "feed_position": "Bottom",
        "blank_min_length": 11,
        "blank_min_width": 25,
        "blank_max_length": 102,
        "blank_max_width": 220,
        "can_print": 0,
        "can_score_slot": 1,
        "can_die_cut": 0,
        "can_glue": 0,
        "can_stitch": 0,
        "can_fold": 0,
        "hand_feed": 1,
        "rate_msf": 12,
        "setup_time_min": 15,
        "setup_cost": 30,
        "special_notes": '20 3/8" knives and 7" knives. Must have 60" between knives. '
                         'Has access holes HH and CO. Hand Feed must be 25" through machine.',
    },
    {
        "machine_id": "130",
        "machine_name": "2-Color Ward RDC",
        "department": "Die Cut",
        "enabled": 1,
        "speed_value": 200,
        "speed_unit": "per minute",
        "tops": 2,
        "feed_position": "Bottom",
        "blank_min_length": 20,
        "blank_min_width": 25,
        "blank_max_length": 75,
        "blank_max_width": 110,
        "can_print": 1,
        "print_stations": 2,
        "can_score_slot": 0,
        "can_die_cut": 1,
        "die_cut_position": "Top",
        "can_glue": 0,
        "can_stitch": 0,
        "can_fold": 0,
        "feed_edge": "LE (Leading Edge)",
        "cutting_surface_width": 64,
        "trim_allowance": 0.5,
        "rate_msf": 45,
        "setup_time_min": 30,
        "setup_cost": 75,
        "special_notes": '64" cutting surface. Trim 1/2" all the way around all board grades. LE feed.',
    },
    {
        "machine_id": "135",
        "machine_name": "Haire Flatbed DC",
        "department": "Die Cut",
        "enabled": 1,
        "speed_value": 50,
        "speed_unit": "per hour",
        "tops": 0,
        "blank_min_length": 10,
        "blank_min_width": 10,
        "blank_max_length": 60,
        "blank_max_width": 80,
        "can_print": 0,
        "can_score_slot": 0,
        "can_die_cut": 1,
        "die_cut_position": "Top",
        "can_glue": 0,
        "can_stitch": 0,
        "can_fold": 0,
        "trim_allowance": 0.5,
        "rate_msf": 35,
        "setup_time_min": 45,
        "setup_cost": 90,
        "special_notes": "Roller bed flat bed. Lower speed but handles complex die shapes.",
    },
    {
        "machine_id": "150",
        "machine_name": 'J&L 130" SFG',
        "department": "Specialty",
        "enabled": 1,
        "speed_value": 0,
        "speed_unit": "per hour",
        "blank_min_length": 13,
        "blank_min_width": 10,
        "blank_max_length": 54,
        "blank_max_width": 130,
        "can_print": 0,
        "can_score_slot": 0,
        "can_die_cut": 0,
        "can_glue": 1,
        "glue_type": "Inside/Outside",
        "glue_tab_inches": 4,
        "can_stitch": 0,
        "can_fold": 1,
        "rate_msf": 40,
        "setup_time_min": 30,
        "setup_cost": 60,
        "special_notes": "Straight Line / Trays / Lock Bottoms. Refer to manual on min's and max's.",
    },
    {
        "machine_id": "161",
        "machine_name": "2-Piece Stitcher",
        "department": "Stitch",
        "enabled": 1,
        "speed_value": 0,
        "speed_unit": "per hour",
        "blank_min_length": 11,
        "blank_min_width": 23,
        "blank_max_length": 102,
        "blank_max_width": 220,
        "can_print": 0,
        "can_score_slot": 0,
        "can_die_cut": 0,
        "can_glue": 0,
        "can_stitch": 1,
        "can_fold": 0,
        "glue_tab_inches": 3,
        "rate_msf": 30,
        "setup_time_min": 20,
        "setup_cost": 40,
        "special_notes": "2-Piece Stitcher. Stitch joining method. 3\" tab.",
    },
    {
        "machine_id": "110",
        "machine_name": "Slitter/Scorer",
        "department": "Score/Slot",
        "enabled": 1,
        "speed_value": 0,
        "speed_unit": "per hour",
        "blank_min_length": 15,
        "blank_min_width": 12,
        "blank_max_length": 120,
        "blank_max_width": 117,
        "can_print": 0,
        "can_score_slot": 1,
        "can_die_cut": 0,
        "can_glue": 0,
        "can_stitch": 0,
        "can_fold": 0,
        "max_scores": 6,
        "max_slit_scores": 6,
        "max_knives": 8,
        "min_score_distance": 1,
        "head_width": 2.25,
        "rate_msf": 12,
        "setup_time_min": 10,
        "setup_cost": 20,
        "special_notes": 'Min Distance between scores is 1". 2 1/4" wide heads.',
    },
]


def create_default_machines():
    """Insert all Lexington machines if they don't already exist."""
    for m in LEXINGTON_MACHINES:
        if not frappe.db.exists("Corrugated Machine", m["machine_id"]):
            doc = frappe.new_doc("Corrugated Machine")
            doc.update(m)
            doc.insert(ignore_permissions=True)
            frappe.db.commit()


def create_demo_part_kits():
    """Create 3 demo Part Kit records for auto-part shipping examples."""

    DEMO_KITS = [
        {
            "kit_name": "Automotive Grille Shipping Kit",
            "description": "RSC box with PE foam end caps and cradle insert for shipping automotive grilles",
            "wall_type": "Single Wall",
            "parts": [
                {"part_type": "Box Body", "box_style": "RSC", "length": 36, "width": 24, "depth": 8, "quantity_per_kit": 1},
                {"part_type": "Pad", "length": 24, "width": 8, "depth": 1, "quantity_per_kit": 2},
                {"part_type": "Insert", "length": 36, "width": 24, "depth": 2, "quantity_per_kit": 1},
            ],
        },
        {
            "kit_name": "Chevy 350 Small Block Engine Kit",
            "description": "Heavy-duty BLISS box with corner foam blocks and top/bottom pads for engine shipping",
            "wall_type": "Double Wall",
            "parts": [
                {"part_type": "Box Body", "box_style": "BLISS", "length": 30, "width": 24, "depth": 26, "quantity_per_kit": 1},
                {"part_type": "Pad", "length": 6, "width": 6, "depth": 24, "quantity_per_kit": 4},
                {"part_type": "Pad", "length": 30, "width": 24, "depth": 2, "quantity_per_kit": 1},
                {"part_type": "Pad", "length": 30, "width": 24, "depth": 2, "quantity_per_kit": 1},
            ],
        },
        {
            "kit_name": "Lawn Mower Axle Shipping Kit",
            "description": "Long RSC box with foam end cradles and wrap sleeve for axle protection",
            "wall_type": "Single Wall",
            "parts": [
                {"part_type": "Box Body", "box_style": "RSC", "length": 42, "width": 8, "depth": 8, "quantity_per_kit": 1},
                {"part_type": "Pad", "length": 8, "width": 8, "depth": 4, "quantity_per_kit": 2},
                {"part_type": "Liner", "length": 42, "width": 8, "depth": 0.5, "quantity_per_kit": 1},
            ],
        },
    ]

    for kit_data in DEMO_KITS:
        if frappe.db.exists("Corrugated Part Kit", {"kit_name": kit_data["kit_name"]}):
            continue

        doc = frappe.new_doc("Corrugated Part Kit")
        doc.kit_name = kit_data["kit_name"]
        doc.description = kit_data["description"]
        doc.wall_type = kit_data["wall_type"]

        for part in kit_data["parts"]:
            row = doc.append("parts", {})
            row.part_type = part["part_type"]
            row.box_style = part.get("box_style", "")
            row.length = part["length"]
            row.width = part["width"]
            row.depth = part.get("depth", 0)
            row.quantity_per_kit = part["quantity_per_kit"]

        doc.insert(ignore_permissions=True)
        frappe.db.commit()


def after_install():
    create_default_machines()
    create_demo_part_kits()
